REDIS_STATUS={
    SET_SUCCESS:{
        success:true,
        status:'CACHE_000',
        description:'缓存设置成功'
    },
    DEL_SUCCESS:{
        success:true,
        status:'CACHE_001',
        description:'缓存删除成功'
    },
    GET_SUCCESS:{
        success:true,
        status:'CACHE_002',
        description:'缓存查询成功'
    },
    SET_FAIL:{
        success:false,
        status:'CACHE_003',
        description:'缓存设置失败'
    },
    DEL_FAIL:{
        success:false,
        status:'CACHE_004',
        description:'缓存删除失败'
    },
    GET_FAIL:{
        success:false,
        status:'CACHE_005',
        description:'缓存查询失败'
    },
    PARAM_ERROR:{
        success:false,
        status:'CACHE_006',
        description:'请求参数有误'
    }
}

DB_STATUS={
    SELECT_FAIL:{
        success:false,
        status:'DB_001',
        description:'数据库查询失败'
    },
    UPDATE_SUCCESS:{},
    DEL_SUCCESS:{},
    PARAM_ERROR:{
        success:false,
        status:'DB_006',
        description:'请求参数有误'
    },
    INSERT_ERROR:{
        success:false,
        status:'DB_007',
        description:'数据库新增记录失败'
    }
}

SERVICE_STATUS={
    COMMON_EXCEPTION:{
        success:false,
        status:'SERVICE_FFF',
        description:'服务异常'
    },
    SEND_EMAIL_VC_SUCCESS:{
        success:true,
        status:'SERVICE_000',
        description:'邮箱验证码发送成功'
    },
    REGISTER_SUCCESS:{
        success:true,
        status:'SERVICE_001',
        description:'用户注册成功'
    },
    LOGIN_SUCCESS:{
        success:true,
        status:'SERVICE_002',
        description:'用户登录成功'
    },
    MAIL_USED:{
        success:false,
        status:'SERVICE_002',
        description:'用户登录成功'
    },
    SEND_EMAIL_VC_FAIL:{
        success:true,
        status:'SERVICE_003',
        description:'邮箱验证码发送失败'
    },
    REGISTER_FAIL:{
        success:true,
        status:'SERVICE_004',
        description:'用户注册失败'
    },
    LOGIN_FAIL:{
        success:true,
        status:'SERVICE_005',
        description:'用户登录失败'
    },
    LOGOUT_SUCCESS:{
        success:true,
        status:'SERVICE_005',
        description:'用户退出登录成功'
    },
    LOGOUT_FAIL:{
        success:false,
        status:'SERVICE_005',
        description:'用户退出登录失败'
    },
    PARAM_ERROR:{
        success:false,
        status:'SERVICE_006',
        description:'请求参数错误'
    },
    ACCOUNT_LOCKED:{
        success:false,
        status:'SERVICE_007',
        description:'账号被锁定'
    },
    NOT_LOGIN:{
        success:false,
        status:'SERVICE_008',
        description:'用户未登录'
    },
    GET_MEMO_SUCCESS:{
        success:true,
        status:'SERVICE_009',
        description:'便签查询成功'
    },
    MEMO_SET_TOP_SUCCESS:{
        success:true,
        status:'SERVICE_010',
        description:'便签置顶或取消置顶成功'
    },
    MEMO_SET_TOP_FAIL:{
        success:false,
        status:'SERVICE_011',
        description:'便签置顶或取消置顶失败'
    },
    ACCOUNT_PASSWORD_NOT_MATCHED:{
        success:false,
        status:'SERVICE_012',
        description:'账号密码不匹配'
    },
    DEL_MEMO_FAIL:{
        success:false,
        status:'SERVICE_013',
        description:'删除或彻底删除便签失败'
    },
    DEL_MEMO_SUCCESS:{
        success:true,
        status:'SERVICE_014',
        description:'删除便签成功'
    },
    ADD_MEMO_SUCCESS:{
        success:true,
        status:'SERVICE_015',
        description:'新增便签成功'
    },
    ADD_MEMO_FAIL:{
        success:false,
        status:'SERVICE_016',
        description:'新增便签失败'
    },
    MAIL_NOTIFICATION:{
        success:false,
        status:'SERVICE_017',
        description:'通知邮件发送失败'
    },
    UPDATE_MEMO_SUCCESS:{
        success:true,
        status:'SERVICE_018',
        description:'更新便签成功'
    },
    UPDATE_MEMO_FAIL:{
        success:false,
        status:'SERVICE_019',
        description:'更新便签失败'
    },
    GET_NOTE_SUCCESS:{
        success:true,
        status:'SERVICE_020',
        description:'获取用户笔记成功'
    },
    GET_NOTE_FAIL:{
        success:false,
        status:'SERVICE_021',
        description:'获取用户笔记失败'
    },
    GET_NOTEBOOK_SUCCESS:{
        success:true,
        status:'SERVICE_020',
        description:'获取用户笔记本成功'
    },
    GET_NOTEBOOK_FAIL:{
        success:false,
        status:'SERVICE_021',
        description:'获取用户笔记本失败'
    },
    NOTE_SET_TOP_SUCCESS:{
        success:true,
        status:'SERVICE_022',
        description:'便签置顶或取消置顶成功'
    },
    NOTE_SET_TOP_FAIL:{
        success:false,
        status:'SERVICE_023',
        description:'便签置顶或取消置顶失败'
    },
    DEL_NOTE_FAIL:{
        success:false,
        status:'SERVICE_024',
        description:'删除或彻底删除笔记失败'
    },
    DEL_NOTE_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'删除或彻底删除笔记成功'
    },
    ADD_NOTE_SUCCESS:{
        success:true,
        status:'SERVICE_026',
        description:'新增笔记成功'
    },
    ADD_NOTE_FAIL:{
        success:false,
        status:'SERVICE_027',
        description:'新增笔记失败'
    },
    UPDATE_NOTE_SUCCESS:{
        success:true,
        status:'SERVICE_028',
        description:'更新笔记成功'
    },
    UPDATE_NOTE_FAIL:{
        success:false,
        status:'SERVICE_029',
        description:'更新笔记失败'
    },
    GET_USERINFO_SUCCESS:{
        success:true,
        status:'SERVICE_030',
        description:'查询用户信息成功'
    },
    GET_USERINFO_FAIL:{
        success:false,
        status:'SERVICE_031',
        description:'查询用户信息失败'
    },
    DEL_FILE_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'删除文件成功'
    },
    DEL_FILE_FAIL:{
        success:false,
        status:'SERVICE_025',
        description:'删除文件失败'
    },
    COMPLETE_DEL_FILE_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'彻底删除文件成功'
    },
    COMPLETE_DEL_FILE_FAIL:{
        success:false,
        status:'SERVICE_025',
        description:'彻底删除文件失败'
    },
    GET_DUMPSTER_FILE_LIST_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'彻底删除文件成功'
    },
    GET_DUMPSTER_FILE_LIST_FAIL:{
        success:false,
        status:'SERVICE_025',
        description:'彻底删除文件失败'
    },
    RESTORE_FILE_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'恢复文件成功'
    },
    RESTORE_FILE_FAIL:{
        success:false,
        status:'SERVICE_025',
        description:'恢复文件失败'
    },
    UPDATE_USER_INFO_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'更新用户信息成功'
    },
    UPDATE_USER_INFO_FAIL:{
        success:false,
        status:'SERVICE_025',
        description:'更新用户信息失败'
    },
    UPDATE_USER_AVATAR_SUCCESS:{
        success:true,
        status:'SERVICE_025',
        description:'更新用户头像成功'
    },
    UPDATE_USER_AVATAR_FAIL:{
        success:false,
        status:'SERVICE_025',
        description:'更新用户头像失败'
    },
}

EVENT_LIST = {
    USER_REGIST:{
        code:'0',
        desc:'用户注册'
    },
    LOGIN_MAIL_PASSWORD:{
        code:'1',
        desc:'邮箱密码登录'
    },
    MEMO_SET_TOP:{
        code:'2',
        desc:'便签置顶'
    },
    MEMO_UNSET_TOP:{
        code:'3',
        desc:'便签取消置顶'
    },
    MEMO_DEL:{
        code:'4',
        desc:'删除便签'
    },
    MEMO_COMPEL_DEL:{
        code:'5',
        desc:'彻底删除便签'
    },
    ADD_MEMO:{
        code:'6',
        desc:'新增便签'
    },
    UPDATE_MEMO:{
        code:'7',
        desc:'更新便签'
    },
    NOTE_SET_TOP:{
        code:'8',
        desc:'笔记置顶'
    },
    NOTE_UNSET_TOP:{
        code:'9',
        desc:'笔记取消置顶'
    },
    NOTE_DEL:{
        code:'10',
        desc:'删除笔记'
    },
    NOTE_COMPEL_DEL:{
        code:'11',
        desc:'彻底删除笔记'
    },
    ADD_NOTE:{
        code:'12',
        desc:'新增笔记'
    },
    UPDATE_NOTE:{
        code:'13',
        desc:'更新笔记'
    },
    RESTORE_NOTE:{
        code:'13',
        desc:'恢复笔记'
    },
    RESTORE_MEMO:{
        code:'13',
        desc:'恢复便签'
    },
    QUERY_USER_INFO:{
        code:'13',
        desc:'查询用户信息'
    },
    UPDATE_USER_INFO:{
        code:'13',
        desc:'更新用户信息'
    },
    UPDATE_USER_AVATAR:{
        code:'13',
        desc:'更新用户头像'
    },
}

module.exports = {REDIS_STATUS,DB_STATUS,SERVICE_STATUS,EVENT_LIST}