const noteApi = {
    getRecentNoteList:{
        name:'获取最近访问笔记列表',
        url:'/note/getRecentNoteList',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    getUserNoteList:{
        name:'获取笔记本内的笔记列表',
        url:'/note/getUserNoteList',
        method:'GET',
        userAuth:true,
        dataParam:true,
        successMessage:false
    },
    topNote:{
        name:['置顶笔记','取消置顶笔记'],
        url:'/note/setNoteTop',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    createNote:{
        name:'创建笔记',
        url:'/note/createNote',
        method:'PUT',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    saveNote:{
        name:'保存笔记',
        url:'/note/saveNote',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    getNoteInfo:{
        name:'获取笔记信息',
        url:'/note/getNoteInfo',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    }
}

export default noteApi