const feedbackApi = {
    addDemand:{
        name:'提交需求',
        url:'/feedback/addDemand',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    addIssue:{
        name:'提交问题',
        url:'/feedback/addIssue',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    getDemandList:{
        name:'获取需求列表',
        url:'/feedback/getDemandList',
        method:'GET',
        userAuth:false,
        dataParam:false,
        successMessage:false
    },
    getIssueList:{
        name:'获取问题列表',
        url:'/feedback/getIssueList',
        method:'GET',
        userAuth:false,
        dataParam:false,
        successMessage:false
    },
    getDemandDetail:{
        name:'获取需求详情',
        url:'/feedback/getDemandDetail',
        method:'GET',
        userAuth:false,
        dataParam:false,
        successMessage:false
    },
    addComment:{
        name:'发表需求评论',
        url:'/feedback/addComment',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    voteDemand:{
        name:'需求投票',
        url:'/feedback/voteDemand',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    }
}

export default feedbackApi
