const noteApi = {
    getRecentNoteList:{
        name:'获取最近访问笔记列表',
        url:'/note/getRecentNoteList',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    getUserNoteList:{
        name:'获取笔记本内的笔记列表',
        url:'/note/getUserNoteList',
        method:'GET',
        userAuth:true,
        dataParam:true,
        successMessage:false
    },
    topNote:{
        name:['置顶笔记','取消置顶笔记'],
        url:'/note/setNoteTop',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    publicNote:{
        name:['公开笔记','私有化笔记'],
        url:'/note/setNoteOpenStatus',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    renameNote:{
        name:'笔记重命名',
        url:'/note/renameNote',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    createNote:{
        name:'创建笔记',
        url:'/note/createNote',
        method:'PUT',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    saveNote:{
        name:'保存笔记',
        url:'/note/saveNote',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    getNoteInfo:{
        name:'获取笔记信息',
        url:'/note/getNoteInfo',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    getOpenNoteList:{
        name:'获取公开笔记列表',
        url:'/note/getOpenNoteList',
        method:'GET',
        userAuth:false,
        dataParam:true,
        successMessage:false
    },
    getNotePublicInfo:{
        name:'获取公开笔记信息',
        url:'/note/getPublicNoteInfo',
        method:'GET',
        userAuth:false,
        dataParam:false,
        successMessage:false
    },
    getUserAllNoteList:{
        name:'获取我的全部文章',
        url:'/note/getUserAllNoteList',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    deleteNote:{
        name:'删除笔记',
        url:'/note/deleteNote',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },

    // ===== 日记 / 待办 =====
    getDiary:{
        name:'获取日记与待办',
        url:'/diary/getDiary',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    getDiaryDateList:{
        name:'获取日记日期列表',
        url:'/diary/getDiaryDateList',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    saveDiary:{
        name:'保存日记',
        url:'/diary/saveDiary',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    deleteDiary:{
        name:'删除日记',
        url:'/diary/deleteDiary',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    //待办为树形结构，必须以 JSON 提交，故 dataParam 保持 false
    saveTodo:{
        name:'保存待办事项',
        url:'/diary/saveTodo',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    deleteTodo:{
        name:'删除待办事项',
        url:'/diary/deleteTodo',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
}

export default noteApi