const notebookApi = {
    getNotebookList:{
        name:'获取笔记本列表',
        url:'/notebook/getUserNotebookList',
        method:'GET',
        userAuth:true,
        dataParam:false,
        successMessage:false
    },
    addNotebook:{
        name:'新增笔记本',
        url:'/notebook/addNotebook',
        method:'POST',
        userAuth:true,
        dataParam:true,
        successMessage:true
    },
    renameNotebook:{
        name:'笔记本重命名',
        url:'/notebook/renameNotebook',
        method:'POST',
        userAuth:true,
        dataParam:true,
        successMessage:true
    },
    deleteNotebook:{
        name:['删除笔记本','彻底删除笔记本'],
        url:'/note/deleteNotebook',
        method:'DELETE',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
    updateNotebookRelation:{
        name:'更新笔记本关系',
        url:'/notebook/updateNotebookRelation',
        method:'POST',
        userAuth:true,
        dataParam:false,
        successMessage:true
    },
}

export default notebookApi